SWEP.Base = "tfa_ava_luger"
SWEP.Category = "TFA AVA" --The category.  Please, just choose something generic or something I"ve already done if you plan on only doing like one swep..
SWEP.Spawnable = true
SWEP.AdminSpawnable = true
SWEP.PrintName = "Luger P-08 [Dragoon]"
SWEP.Spawnable = true
SWEP.AdminOnly = false
SWEP.Skin = 1
SWEP.Primary.DefaultClip = 48