SWEP.Base = "tfa_ava_deagle"
SWEP.Category = "TFA AVA" --The category.  Please, just choose something generic or something I"ve already done if you plan on only doing like one swep..
SWEP.Spawnable = true
SWEP.AdminSpawnable = true
SWEP.PrintName = "Desert Eagle [Urushi]"
SWEP.Spawnable = true
SWEP.AdminOnly = false
SWEP.Skin = 5
SWEP.Primary.DefaultClip = 42